// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/login.proto

package com.zhaoyan.communication.protocol.pb;

public final class PBLoginProtos {
  private PBLoginProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.zhaoyan.juyou.PBLoginResult}
   */
  public enum PBLoginResult
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 1;</code>
     */
    SUCCESS(0, 1),
    /**
     * <code>FAIL = 2;</code>
     */
    FAIL(1, 2),
    ;

    /**
     * <code>SUCCESS = 1;</code>
     */
    public static final int SUCCESS_VALUE = 1;
    /**
     * <code>FAIL = 2;</code>
     */
    public static final int FAIL_VALUE = 2;


    public final int getNumber() { return value; }

    public static PBLoginResult valueOf(int value) {
      switch (value) {
        case 1: return SUCCESS;
        case 2: return FAIL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBLoginResult>() {
            public PBLoginResult findValueByNumber(int number) {
              return PBLoginResult.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.getDescriptor().getEnumTypes().get(0);
    }

    private static final PBLoginResult[] VALUES = values();

    public static PBLoginResult valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBLoginResult(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.PBLoginResult)
  }

  /**
   * Protobuf enum {@code com.zhaoyan.juyou.PBLoginFailReason}
   */
  public enum PBLoginFailReason
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKOWN = 1;</code>
     */
    UNKOWN(0, 1),
    ;

    /**
     * <code>UNKOWN = 1;</code>
     */
    public static final int UNKOWN_VALUE = 1;


    public final int getNumber() { return value; }

    public static PBLoginFailReason valueOf(int value) {
      switch (value) {
        case 1: return UNKOWN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PBLoginFailReason>() {
            public PBLoginFailReason findValueByNumber(int number) {
              return PBLoginFailReason.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.getDescriptor().getEnumTypes().get(1);
    }

    private static final PBLoginFailReason[] VALUES = values();

    public static PBLoginFailReason valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private PBLoginFailReason(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.zhaoyan.juyou.PBLoginFailReason)
  }

  public interface PBLoginRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required int32 headImageId = 2;
    /**
     * <code>required int32 headImageId = 2;</code>
     */
    boolean hasHeadImageId();
    /**
     * <code>required int32 headImageId = 2;</code>
     */
    int getHeadImageId();

    // optional bytes headImageData = 3;
    /**
     * <code>optional bytes headImageData = 3;</code>
     */
    boolean hasHeadImageData();
    /**
     * <code>optional bytes headImageData = 3;</code>
     */
    com.google.protobuf.ByteString getHeadImageData();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBLoginRequest}
   */
  public static final class PBLoginRequest extends
      com.google.protobuf.GeneratedMessage
      implements PBLoginRequestOrBuilder {
    // Use PBLoginRequest.newBuilder() to construct.
    private PBLoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBLoginRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBLoginRequest defaultInstance;
    public static PBLoginRequest getDefaultInstance() {
      return defaultInstance;
    }

    public PBLoginRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              headImageId_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              headImageData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<PBLoginRequest> PARSER =
        new com.google.protobuf.AbstractParser<PBLoginRequest>() {
      public PBLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBLoginRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBLoginRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 headImageId = 2;
    public static final int HEADIMAGEID_FIELD_NUMBER = 2;
    private int headImageId_;
    /**
     * <code>required int32 headImageId = 2;</code>
     */
    public boolean hasHeadImageId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 headImageId = 2;</code>
     */
    public int getHeadImageId() {
      return headImageId_;
    }

    // optional bytes headImageData = 3;
    public static final int HEADIMAGEDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString headImageData_;
    /**
     * <code>optional bytes headImageData = 3;</code>
     */
    public boolean hasHeadImageData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes headImageData = 3;</code>
     */
    public com.google.protobuf.ByteString getHeadImageData() {
      return headImageData_;
    }

    private void initFields() {
      name_ = "";
      headImageId_ = 0;
      headImageData_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeadImageId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, headImageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, headImageData_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, headImageId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, headImageData_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.gen.PBLoginProtos.PBLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        headImageId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        headImageData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest build() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest result = new com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.headImageId_ = headImageId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.headImageData_ = headImageData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasHeadImageId()) {
          setHeadImageId(other.getHeadImageId());
        }
        if (other.hasHeadImageData()) {
          setHeadImageData(other.getHeadImageData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasHeadImageId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required int32 headImageId = 2;
      private int headImageId_ ;
      /**
       * <code>required int32 headImageId = 2;</code>
       */
      public boolean hasHeadImageId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 headImageId = 2;</code>
       */
      public int getHeadImageId() {
        return headImageId_;
      }
      /**
       * <code>required int32 headImageId = 2;</code>
       */
      public Builder setHeadImageId(int value) {
        bitField0_ |= 0x00000002;
        headImageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 headImageId = 2;</code>
       */
      public Builder clearHeadImageId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        headImageId_ = 0;
        onChanged();
        return this;
      }

      // optional bytes headImageData = 3;
      private com.google.protobuf.ByteString headImageData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes headImageData = 3;</code>
       */
      public boolean hasHeadImageData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes headImageData = 3;</code>
       */
      public com.google.protobuf.ByteString getHeadImageData() {
        return headImageData_;
      }
      /**
       * <code>optional bytes headImageData = 3;</code>
       */
      public Builder setHeadImageData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        headImageData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes headImageData = 3;</code>
       */
      public Builder clearHeadImageData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        headImageData_ = getDefaultInstance().getHeadImageData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBLoginRequest)
    }

    static {
      defaultInstance = new PBLoginRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBLoginRequest)
  }

  public interface PBLoginRespondOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.zhaoyan.juyou.PBLoginResult result = 1;
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    boolean hasResult();
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult();

    // optional int32 userId = 2;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional int32 userId = 2;</code>
     */
    int getUserId();

    // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    boolean hasFailReason();
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason();
  }
  /**
   * Protobuf type {@code com.zhaoyan.juyou.PBLoginRespond}
   */
  public static final class PBLoginRespond extends
      com.google.protobuf.GeneratedMessage
      implements PBLoginRespondOrBuilder {
    // Use PBLoginRespond.newBuilder() to construct.
    private PBLoginRespond(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBLoginRespond(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBLoginRespond defaultInstance;
    public static PBLoginRespond getDefaultInstance() {
      return defaultInstance;
    }

    public PBLoginRespond getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBLoginRespond(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult value = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                result_ = value;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason value = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                failReason_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.Builder.class);
    }

    public static com.google.protobuf.Parser<PBLoginRespond> PARSER =
        new com.google.protobuf.AbstractParser<PBLoginRespond>() {
      public PBLoginRespond parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBLoginRespond(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBLoginRespond> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.zhaoyan.juyou.PBLoginResult result = 1;
    public static final int RESULT_FIELD_NUMBER = 1;
    private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult result_;
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult() {
      return result_;
    }

    // optional int32 userId = 2;
    public static final int USERID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 userId = 2;</code>
     */
    public int getUserId() {
      return userId_;
    }

    // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
    public static final int FAILREASON_FIELD_NUMBER = 3;
    private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason failReason_;
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    public boolean hasFailReason() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
     */
    public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason() {
      return failReason_;
    }

    private void initFields() {
      result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
      userId_ = 0;
      failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, failReason_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, result_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, failReason_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zhaoyan.juyou.PBLoginRespond}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespondOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.class, com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.Builder.class);
      }

      // Construct using com.zhaoyan.communication.protocol.gen.PBLoginProtos.PBLoginRespond.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond getDefaultInstanceForType() {
        return com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.getDefaultInstance();
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond build() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond buildPartial() {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond result = new com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.result_ = result_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userId_ = userId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.failReason_ = failReason_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond) {
          return mergeFrom((com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond other) {
        if (other == com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond.getDefaultInstance()) return this;
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasFailReason()) {
          setFailReason(other.getFailReason());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasResult()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginRespond) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.zhaoyan.juyou.PBLoginResult result = 1;
      private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult getResult() {
        return result_;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public Builder setResult(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.zhaoyan.juyou.PBLoginResult result = 1;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000001);
        result_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginResult.SUCCESS;
        onChanged();
        return this;
      }

      // optional int32 userId = 2;
      private int userId_ ;
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 userId = 2;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      // optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;
      private com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public boolean hasFailReason() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason getFailReason() {
        return failReason_;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public Builder setFailReason(com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        failReason_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .com.zhaoyan.juyou.PBLoginFailReason failReason = 3;</code>
       */
      public Builder clearFailReason() {
        bitField0_ = (bitField0_ & ~0x00000004);
        failReason_ = com.zhaoyan.communication.protocol.pb.PBLoginProtos.PBLoginFailReason.UNKOWN;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zhaoyan.juyou.PBLoginRespond)
    }

    static {
      defaultInstance = new PBLoginRespond(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zhaoyan.juyou.PBLoginRespond)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017src/login.proto\022\021com.zhaoyan.juyou\"J\n\016" +
      "PBLoginRequest\022\014\n\004name\030\001 \002(\t\022\023\n\013headImag" +
      "eId\030\002 \002(\005\022\025\n\rheadImageData\030\003 \001(\014\"\214\001\n\016PBL" +
      "oginRespond\0220\n\006result\030\001 \002(\0162 .com.zhaoya" +
      "n.juyou.PBLoginResult\022\016\n\006userId\030\002 \001(\005\0228\n" +
      "\nfailReason\030\003 \001(\0162$.com.zhaoyan.juyou.PB" +
      "LoginFailReason*&\n\rPBLoginResult\022\013\n\007SUCC" +
      "ESS\020\001\022\010\n\004FAIL\020\002*\037\n\021PBLoginFailReason\022\n\n\006" +
      "UNKOWN\020\001B7\n&com.zhaoyan.communication.pr" +
      "otocol.genB\rPBLoginProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zhaoyan_juyou_PBLoginRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBLoginRequest_descriptor,
              new java.lang.String[] { "Name", "HeadImageId", "HeadImageData", });
          internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_zhaoyan_juyou_PBLoginRespond_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zhaoyan_juyou_PBLoginRespond_descriptor,
              new java.lang.String[] { "Result", "UserId", "FailReason", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
